// @generated by protobuf-ts 2.7.0
// @generated from protobuf file "offer.proto" (package "offerpb", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Offer } from "./offer";
import type { UpdatePartnerRatingResponse } from "./offer";
import type { UpdatePartnerRatingRequest } from "./offer";
import type { UpdatePartnerTotalOrderResponse } from "./offer";
import type { UpdatePartnerTotalOrderRequest } from "./offer";
import type { GetOfferDetailsResponse } from "./offer";
import type { GetOfferDetailsRequest } from "./offer";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetOfferStreamResponse } from "./offer";
import type { GetOfferStreamRequest } from "./offer";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service offerpb.Offer
 */
export interface IOfferClient {
    /**
     * @generated from protobuf rpc: GetOfferStream(offerpb.GetOfferStreamRequest) returns (stream offerpb.GetOfferStreamResponse);
     */
    getOfferStream(input: GetOfferStreamRequest, options?: RpcOptions): ServerStreamingCall<GetOfferStreamRequest, GetOfferStreamResponse>;
    /**
     * @generated from protobuf rpc: GetOfferDetails(offerpb.GetOfferDetailsRequest) returns (offerpb.GetOfferDetailsResponse);
     */
    getOfferDetails(input: GetOfferDetailsRequest, options?: RpcOptions): UnaryCall<GetOfferDetailsRequest, GetOfferDetailsResponse>;
    /**
     * @generated from protobuf rpc: UpdatePartnerTotalOrder(offerpb.UpdatePartnerTotalOrderRequest) returns (offerpb.UpdatePartnerTotalOrderResponse);
     */
    updatePartnerTotalOrder(input: UpdatePartnerTotalOrderRequest, options?: RpcOptions): UnaryCall<UpdatePartnerTotalOrderRequest, UpdatePartnerTotalOrderResponse>;
    /**
     * @generated from protobuf rpc: UpdatePartnerRating(offerpb.UpdatePartnerRatingRequest) returns (offerpb.UpdatePartnerRatingResponse);
     */
    updatePartnerRating(input: UpdatePartnerRatingRequest, options?: RpcOptions): UnaryCall<UpdatePartnerRatingRequest, UpdatePartnerRatingResponse>;
}
/**
 * @generated from protobuf service offerpb.Offer
 */
export class OfferClient implements IOfferClient, ServiceInfo {
    typeName = Offer.typeName;
    methods = Offer.methods;
    options = Offer.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetOfferStream(offerpb.GetOfferStreamRequest) returns (stream offerpb.GetOfferStreamResponse);
     */
    getOfferStream(input: GetOfferStreamRequest, options?: RpcOptions): ServerStreamingCall<GetOfferStreamRequest, GetOfferStreamResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOfferStreamRequest, GetOfferStreamResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOfferDetails(offerpb.GetOfferDetailsRequest) returns (offerpb.GetOfferDetailsResponse);
     */
    getOfferDetails(input: GetOfferDetailsRequest, options?: RpcOptions): UnaryCall<GetOfferDetailsRequest, GetOfferDetailsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOfferDetailsRequest, GetOfferDetailsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePartnerTotalOrder(offerpb.UpdatePartnerTotalOrderRequest) returns (offerpb.UpdatePartnerTotalOrderResponse);
     */
    updatePartnerTotalOrder(input: UpdatePartnerTotalOrderRequest, options?: RpcOptions): UnaryCall<UpdatePartnerTotalOrderRequest, UpdatePartnerTotalOrderResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerTotalOrderRequest, UpdatePartnerTotalOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePartnerRating(offerpb.UpdatePartnerRatingRequest) returns (offerpb.UpdatePartnerRatingResponse);
     */
    updatePartnerRating(input: UpdatePartnerRatingRequest, options?: RpcOptions): UnaryCall<UpdatePartnerRatingRequest, UpdatePartnerRatingResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePartnerRatingRequest, UpdatePartnerRatingResponse>("unary", this._transport, method, opt, input);
    }
}
